namespace ZmkCompanion.Core;

// Projects the user's AutoStartEntry list into a single Windows Startup .bat.
// Deliberately never called automatically (no "sync on save", no background
// timer): every write is the direct result of the user clicking "Escribir en
// inicio de Windows" in CellGridEditorForm, and the exact content is shown to
// them first. An app that silently drops files into the Startup folder on its
// own is indistinguishable, to an antivirus or to the user, from a persistence
// mechanism, so this stays opt-in and visible at every step.
static class AutoStartManager
{
    // App-specific name, deliberately not something generic like "startup.bat"
    // that could collide with an unrelated file already in that folder.
    public const string FileName = "ZmkCompanionAutoStart.bat";

    public static string StartupFolder =>
        Environment.GetFolderPath(Environment.SpecialFolder.Startup);

    public static string BatPath => Path.Combine(StartupFolder, FileName);

    // 15s: covers ZmkCompanion.exe's own login-time startup (BLE scan, pipe
    // server bring-up) before a zkc send would otherwise hit "tray not
    // running" — see CliRunner.Connect's 3s pipe-connect timeout. Windows
    // doesn't order "at logon" startup items relative to each other, so this
    // is a fixed guess, not a guarantee.
    private const int StartupDelaySeconds = 15;

    // Each entry launches via `start` so a long-running --watch entry never
    // blocks the ones after it in the file, they're independent processes,
    // not a sequential script. /min keeps the console out of the way without
    // hiding it entirely, hidden-and-silent is indistinguishable from malware
    // staging a background process.
    public static string BuildBatContent(IEnumerable<AutoStartEntry> entries)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine(":: Auto-generated by ZmkCompanion, do not edit by hand,");
        sb.AppendLine(":: it gets fully overwritten every time entries change.");
        sb.AppendLine(":: Manage entries from the Canvas editor's \"Inicio automatico\" tab.");
        foreach (var e in entries.Where(e => e.Enabled && e.Command.Trim().Length > 0))
        {
            sb.AppendLine();
            sb.AppendLine($":: === ZmkCompanion: {e.Name} ===");
            sb.AppendLine($"start \"\" /min cmd /c \"timeout /t {StartupDelaySeconds} /nobreak >nul & {e.Command}\"");
            sb.AppendLine($":: === fin {e.Name} ===");
        }
        return sb.ToString();
    }

    // Writes the regenerated .bat, or deletes it if there's nothing enabled
    // to run, so disabling every entry actually removes the Startup entry
    // instead of leaving a file that runs nothing but still exists. Returns
    // the resulting path (written) or null (deleted / nothing to write).
    public static string? Apply(IReadOnlyList<AutoStartEntry> entries)
    {
        bool anyEnabled = entries.Any(e => e.Enabled && e.Command.Trim().Length > 0);
        if (!anyEnabled)
        {
            if (File.Exists(BatPath)) File.Delete(BatPath);
            return null;
        }
        File.WriteAllText(BatPath, BuildBatContent(entries));
        return BatPath;
    }
}
